{% set name = "arch" %}
{% set version = "4.14" %}

package:
  name: arch-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 327d0b59261f47f7ebea35baf707338a5ac0e8cc6611d7033b0a66b4bae748ba

build:
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.29.14
    - pip
    - numpy 1.14.*
  run:
    - python
    - cython >=0.29.14
    - numpy >=1.14
    - pandas >=0.23
    - property-cached >=1.6.3
    - scipy >=1.0.1
    - statsmodels >=0.9

test:
  imports:
    - arch

about:
  home: https://github.com/bashtage/arch
  license: NCSA
  license_family: MIT
  license_file: LICENSE.md
  summary: Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for financial econometrics
  description: |
    Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for financial econometrics, written in Python 
    (with Cython and/or Numba used to improve performance)
  doc_url: https://arch.readthedocs.org/en/latest/
  dev_url: https://github.com/bashtage/arch
  home: https://github.com/bashtage/arch

extra:
  recipe-maintainers:
    - DanielBok
